version: '3.7'
services:
  maven17-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_account_system:latest
    container_name: user_account_system
    ports:
      - "8080:8080"
    environment:
      - DRIVERCLASS_NAME=com.mysql.jdbc.Driver
      - PROTOCOL=jdbc
      - SUB_PROTOCOL=mysql
      - fineract_tenants_driver=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/user_account?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: user_account
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
